=== Xutingyuan/PRD2018-G01/code/xml/pbco.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- version 1.01 Edit by 2009-09-22 -->

<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:pbl="http://www.pbcls.org/pbco/"
	targetNamespace="http://www.pbcls.org/pbco/">
	
	<!-- Element Definitions -->

	<element name="description" type="string"></element>

	<element name="version" type="string"></element>

	<element name="author" type="string"></element>

	<element name="email" type="string"></element>

	<element name="creationdate" type="date"></element>

	<element name="lastmodified" type="date"></element>

	<element name="id" type="string"></element>
	
	<element name="name" type="string"></element>

	<element name="role" type="string"></element>

	<element name="resource" type="pbl:resourceType"></element>

	<element name="resources" type="pbl:resourcesType"></element>

	<element name="duration" type="string"></element>
	
	<element name="isparent" type="boolean"></element>
	
	<element name="ismilestone" type="boolean"></element>

	<element name="parentid" type="string"></element>

	<element name="resourceids" type="string"></element>

	<element name="inputs" type="pbl:inputsType"></element>
	
	<element name="file" type="string"></element>

	<element name="outputs" type="pbl:outputsType"></element>

	<element name="predecessorids" type="string"></element>

	<element name="task" type="pbl:taskType"></element>
	
	<element name="wbs" type="string"></element>

	<element name="tasks" type="pbl:tasksType"></element>

	<element name="pbco" type="pbl:pbcoType"></element>

	<!-- ComplexType Definitions -->
	
	<complexType name="inputsType">
		<sequence>
			<element ref="pbl:file" maxOccurs="unbounded"></element>
		</sequence>
	</complexType>
	
	<complexType name="outputsType">
		<sequence>
			<element ref="pbl:file" maxOccurs="unbounded"></element>
		</sequence>
	</complexType>

	<complexType name="resourceType">
		<all>
			<element ref="pbl:id"></element>
			<element ref="pbl:name"></element>
			<element ref="pbl:description" minOccurs="0"></element>
			<element ref="pbl:role"></element>
		</all>
	</complexType>

	<complexType name="resourcesType">
		<sequence>
			<element ref="pbl:resource" maxOccurs="unbounded" minOccurs="1"></element>
		</sequence>
	</complexType>

	<complexType name="taskType">
		<all>
			<element ref="pbl:id"></element>
			<element ref="pbl:name"></element>
			<element ref="pbl:wbs" minOccurs="0"></element>
			<element ref="pbl:description" minOccurs="0"></element>
			<element ref="pbl:isparent" minOccurs="0"></element>
			<element ref="pbl:resourceids" minOccurs="0"></element>
			<element ref="pbl:duration" minOccurs="0"></element>
			<element ref="pbl:ismilestone" minOccurs="0"></element>		
			<element ref="pbl:parentid" minOccurs="0"></element>					
			<element ref="pbl:inputs" minOccurs="0"></element>
			<element ref="pbl:outputs" minOccurs="0"></element>
			<element ref="pbl:predecessorids" minOccurs="0"></element>
		</all>
	</complexType>

	<complexType name="tasksType">
		<sequence>
			<element ref="pbl:task" maxOccurs="unbounded" minOccurs="1"></element>
		</sequence>
	</complexType>

	<complexType name="pbcoType">
		<all>
			<element ref="pbl:name"></element>
			<element ref="pbl:description" minOccurs="0"></element>
			<element ref="pbl:version" minOccurs="0"></element>			
			<element ref="pbl:author" minOccurs="0"></element>
			<element ref="pbl:email" minOccurs="0"></element>
			<element ref="pbl:creationdate" minOccurs="0"></element>
			<element ref="pbl:lastmodified" minOccurs="0"></element>
			<element ref="pbl:resources" minOccurs="0"></element>
			<element ref="pbl:tasks"></element>
		</all>
	</complexType>
</schema>

=== Xutingyuan/PRD2018-G01/code/system/application/uploadedfile/case_12/standard/pbco.xml
<?xml version="1.0" encoding="utf-8"?>
<pbco xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.pbcls.org/pbco/ pbco.xsd" xmlns="http://www.pbcls.org/pbco/">
	<!-- 案例的基本属性 -->
	<name>DS_Project_1_Performance Measurement</name>
	<description></description>
	<version>1.0</version>
	<author>PBCLS</author>
	<email>PBCLS@zju.edu.name</email>
	<creationdate>2010-03-02</creationdate>
	
	<!-- 案例的资源 -->
	<resources>
		<resource>
			<id>1</id>
			<name>Programmer</name>
			<description></description>
			<role>PM</role>
		</resource>	
		<resource>
			<id>2</id>
			<name>Tester</name>
			<description></description>
			<role>Member</role>
		</resource>
		<resource>
			<id>3</id>
			<name>Writer</name>
			<description></description>
			<role>Member</role>
		</resource>
	</resources>	
	
	<!-- 案例任务 -->
	<tasks>
		<task>
			<id>1</id>
			<name>Programming</name>
			<wbs>1</wbs>
			<description>Implement the three functions (30 pts.) and a testing program (20 pts.) with sufficient comments.</description>
			<isparent>0</isparent>
			<resourceids>1</resourceids>
			<duration>9</duration>
			<inputs>
				<file>P1.pdf</file>	
			</inputs>
			<outputs>
				<file>solution.cpp</file>	
			</outputs>
		</task>	
		<task>
			<id>2</id>
			<name>Testing</name>
			<wbs>2</wbs>
			<description>Decide the iteration number K for each test case and fill in the table of results (8 pts.).  Plot the run times of the functions (12 pts.).  Write analysis and comments (10 pts.).</description>
			<isparent>0</isparent>
			<resourceids>2</resourceids>
			<duration>9</duration>
			<inputs>
				<file>P1.pdf</file>	
			</inputs>
			<outputs>
				<file>testcases.txt</file>	
			</outputs>
		</task>					
		<task>
			<id>3</id>
			<name>Report Writing</name>
			<wbs>3</wbs>
			<description>Write Chapter 1 (6 pts.), Chapter 2 (12 pts.), and finally a complete report (2 pts. for overall style of documentation).</description>
			<isparent>0</isparent>
			<resourceids>3</resourceids>
			<predecessorids>1,2</predecessorids>
			<duration>5</duration>
			<inputs>
				<file>Requirements.doc</file>	
			</inputs>
			<outputs>
				<file>report.pdf</file>	
			</outputs>
		</task>			
			
  </tasks>
	
</pbco>

=== Xutingyuan/PRD2018-G01/code/system/application/uploadedfile/case_17/standard/pbco.xml
<?xml version="1.0" encoding="utf-8"?>
<pbco xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.pbcls.org/pbco/ pbco.xsd" xmlns="http://www.pbcls.org/pbco/">
	<!-- 案例的基本属性 -->
	<name>ADS_Project_3 Family of B Trees</name>
	<description></description>
	<version>1.0</version>
	<author>PBCLS</author>
	<email>PBCLS@zju.edu.name</email>
	<creationdate>2010-03-02</creationdate>
	
	<!-- 案例的资源 -->
	<resources>
		<resource>
			<id>1</id>
			<name>Player1</name>
			<description></description>
			<role>PM</role>
		</resource>	
		<resource>
			<id>2</id>
			<name>Player2</name>
			<description></description>
			<role>Member</role>
		</resource>
		<resource>
			<id>3</id>
			<name>Player3</name>
			<description></description>
			<role>Member</role>
		</resource>
	</resources>	
	
	<!-- 案例任务 -->
	<tasks>
		<task>
			<id>1</id>
			<name>Introduction</name>
			<wbs>1</wbs>
			<description>Describe B-tree and its operations (8 pts.).</description>
			<isparent>0</isparent>
			<resourceids>1</resourceids>
			<duration>5</duration>
			<inputs>
				<file>P3.doc</file>	
			</inputs>
			<outputs>
				<file>introduction.doc</file>	
			</outputs>
		</task>	
		<task>
			<id>2</id>
			<name>Analysis</name>
			<wbs>2</wbs>
			<description>Write analysis and comments on B- trees and B+ trees (9 pts.).</description>
			<isparent>0</isparent>
			<resourceids>2</resourceids>
			<duration>5</duration>
			<predecessorids>1</predecessorids>
			<outputs>
				<file>anlysis.doc</file>	
			</outputs>
		</task>					
		<task>
			<id>3</id>
			<name>Documentation Writing</name>
			<wbs>3</wbs>
			<description>Combine all the chapters into a complete report (1 point for overall style of documentation).</description>
			<isparent>0</isparent>
			<resourceids>3</resourceids>
			<duration>2</duration>
			<predecessorids>2</predecessorids>
			<inputs>
				<file>Requirements.doc</file>	
			</inputs>
			<outputs>
				<file>Report.doc</file>	
			</outputs>
		</task>			
		<task>
			<id>4</id>
			<name>Make presentation</name>
			<wbs>4</wbs>
			<description></description>
			<isparent>0</isparent>
			<resourceids>3</resourceids>
			<duration>2</duration>
			<predecessorids>3</predecessorids>
			<inputs>
				<file></file>	
			</inputs>
			<outputs>
				<file>Project.ppt</file>	
			</outputs>
		</task>		
		
					
  </tasks>
	
</pbco>

=== Xutingyuan/PRD2018-G01/code/system/application/uploadedfile/case_16/standard/pbco.xml
<?xml version="1.0" encoding="utf-8"?>
<pbco xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.pbcls.org/pbco/ pbco.xsd" xmlns="http://www.pbcls.org/pbco/">
	<!-- 案例的基本属性 -->
	<name>ADS_Project_2 Population</name>
	<description></description>
	<version>1.0</version>
	<author>PBCLS</author>
	<email>PBCLS@zju.edu.name</email>
	<creationdate>2010-03-02</creationdate>
	
	<!-- 案例的资源 -->
	<resources>
		<resource>
			<id>1</id>
			<name>Programmer</name>
			<description></description>
			<role>PM</role>
		</resource>	
		<resource>
			<id>2</id>
			<name>Tester</name>
			<description></description>
			<role>Member</role>
		</resource>
		<resource>
			<id>3</id>
			<name>Writer</name>
			<description></description>
			<role>Member</role>
		</resource>
	</resources>	
	
	<!-- 案例任务 -->
	<tasks>
		<task>
			<id>1</id>
			<name>Programming</name>
			<wbs>1</wbs>
			<description>Write the program (10 pts.) with sufficient comments.</description>
			<isparent>0</isparent>
			<resourceids>1</resourceids>
			<duration>7</duration>
			<inputs>
				<file>P2.doc</file>	
			</inputs>
			<outputs>
				<file>Source.zip</file>	
			</outputs>
		</task>	
		<task>
			<id>2</id>
			<name>Testing</name>
			<wbs>2</wbs>
			<description>)Provide a set of test cases to fill in a test report (3 pts.).  Write analysis and comments (3 pts.).</description>
			<isparent>0</isparent>
			<resourceids>2</resourceids>
			<duration>7</duration>
			<inputs>
				<file>P2.doc</file>	
			</inputs>
			<outputs>
				<file>Test.zip</file>	
			</outputs>
		</task>					
		<task>
			<id>3</id>
			<name>Documentation Writing</name>
			<wbs>3</wbs>
			<description>Chapter 1 (1 pt.), Chapter 2 (2 pts.), and finally a complete report (1 point for overall style of documentation).</description>
			<isparent>0</isparent>
			<resourceids>3</resourceids>
			<duration>5</duration>
			<predecessorids>1,2</predecessorids>
			<inputs>
				<file>Requirements.doc</file>	
			</inputs>
			<outputs>
				<file>Report.doc</file>	
			</outputs>
		</task>			
		<task>
			<id>4</id>
			<name>Make presentation</name>
			<wbs>4</wbs>
			<description></description>
			<isparent>0</isparent>
			<resourceids>3</resourceids>
			<duration>2</duration>
			<predecessorids>3</predecessorids>
			<inputs>
				<file></file>	
			</inputs>
			<outputs>
				<file>Project.ppt</file>	
			</outputs>
		</task>		
		
					
  </tasks>
	
</pbco>

=== Xutingyuan/PRD2018-G01/code/system/application/uploads/ADS_Project_1  Binary Search Trees/pbco.xml
<?xml version="1.0" encoding="utf-8"?>
<pbco xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.pbcls.org/pbco/ pbco.xsd" xmlns="http://www.pbcls.org/pbco/">
	<!-- 案例的基本属性 -->
	<name>ADS_Project_1  Binary Search Trees</name>
	<description></description>
	<version>1.0</version>
	<author>PBCLS</author>
	<email>PBCLS@zju.edu.name</email>
	<creationdate>2010-03-02</creationdate>
	
	<!-- 案例的资源 -->
	<resources>
		<resource>
			<id>1</id>
			<name>Programmer</name>
			<description></description>
			<role>PM</role>
		</resource>	
		<resource>
			<id>2</id>
			<name>Tester</name>
			<description></description>
			<role>Member</role>
		</resource>
		<resource>
			<id>3</id>
			<name>Writer</name>
			<description></description>
			<role>Member</role>
		</resource>
	</resources>	
	
	<!-- 案例任务 -->
	<tasks>
		<task>
			<id>1</id>
			<name>Programming</name>
			<wbs>1</wbs>
			<description> Implement all the necessary operations on unbalanced binary search trees, AVL trees, and splay trees (6 pts.).  Write a test of performance program (3 pts.).  All the codes must be sufficiently commented.</description>
			<isparent>0</isparent>
			<resourceids>1</resourceids>
			<duration>7</duration>
			<inputs>
				<file>P1.doc</file>	
			</inputs>
			<outputs>
				<file>Source.zip</file>	
			</outputs>
		</task>	
		<task>
			<id>2</id>
			<name>Testing</name>
			<wbs>2</wbs>
			<description>Provide the necessary inputs for testing and give the run time table (2 pts.).  Plot the run times vs. input sizes for illustration (2 pts.).  Write analysis and comments (3 pts.).</description>
			<isparent>0</isparent>
			<resourceids>2</resourceids>
			<duration>7</duration>
			<inputs>
				<file>P1.doc</file>	
			</inputs>
			<outputs>
				<file>Test.zip</file>	
			</outputs>
		</task>					
		<task>
			<id>3</id>
			<name>Documentation Writing</name>
			<wbs>3</wbs>
			<description>Chapter 1 (1 pt.), Chapter 2 (2 pts.), and finally a complete report (1 point for overall style of documentation).</description>
			<isparent>0</isparent>
			<resourceids>3</resourceids>
			<duration>5</duration>
			<predecessorids>1,2</predecessorids>
			<inputs>
				<file>Requirements.doc</file>	
			</inputs>
			<outputs>
				<file>Report.doc</file>	
			</outputs>
		</task>			
		<task>
			<id>4</id>
			<name>Make presentation</name>
			<wbs>4</wbs>
			<description></description>
			<isparent>0</isparent>
			<resourceids>3</resourceids>
			<duration>2</duration>
			<predecessorids>3</predecessorids>
			<inputs>
				<file></file>	
			</inputs>
			<outputs>
				<file>Project.ppt</file>	
			</outputs>
		</task>		
		
					
  </tasks>
	
</pbco>

=== Xutingyuan/PRD2018-G01/code/system/application/uploads/DS_Project_3_Hashing/pbco.xml
<?xml version="1.0" encoding="utf-8"?>
<pbco xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.pbcls.org/pbco/ pbco.xsd" xmlns="http://www.pbcls.org/pbco/">
	<!-- 案例的基本属性 -->
	<name>DS_Project_3_Hashing</name>
	<description></description>
	<version>1.0</version>
	<author>PBCLS</author>
	<email>PBCLS@zju.edu.name</email>
	<creationdate>2010-03-02</creationdate>
	
	<!-- 案例的资源 -->
	<resources>
		<resource>
			<id>1</id>
			<name>Programmer</name>
			<description></description>
			<role>PM</role>
		</resource>	
		<resource>
			<id>2</id>
			<name>Tester</name>
			<description></description>
			<role>Member</role>
		</resource>
		<resource>
			<id>3</id>
			<name>Writer</name>
			<description></description>
			<role>Member</role>
		</resource>
	</resources>	
	
	<!-- 案例任务 -->
	<tasks>
		<task>
			<id>1</id>
			<name>Programming</name>
			<wbs>1</wbs>
			<description>Write the program (50 pts.) with sufficient comments.</description>
			<isparent>0</isparent>
			<resourceids>1</resourceids>
			<duration>9</duration>
			<inputs>
				<file>P3.pdf</file>	
			</inputs>
			<outputs>
				<file>solution.cpp</file>	
			</outputs>
		</task>	
		<task>
			<id>2</id>
			<name>Testing</name>
			<wbs>2</wbs>
			<description>Provide a set of test cases to fill in a test report (20 pts.).  Note that the tester is responsible, as well as the programmer is, for any bug later found by Judge.  Write analysis and comments (10 pts.).</description>
			<isparent>0</isparent>
			<resourceids>2</resourceids>
			<duration>9</duration>
			<inputs>
				<file>P3.pdf</file>	
			</inputs>
			<outputs>
				<file>testcases.txt</file>	
			</outputs>
		</task>					
		<task>
			<id>3</id>
			<name>Report Writing</name>
			<wbs>3</wbs>
			<description>Write Chapter 1 (6 pts.), Chapter 2 (12 pts.), and finally a complete report (2 pts. for overall style of documentation).</description>
			<isparent>0</isparent>
			<resourceids>3</resourceids>
			<predecessorids>1,2</predecessorids>
			<duration>5</duration>
			<inputs>
				<file>Requirements.doc</file>	
			</inputs>
			<outputs>
				<file>report.pdf</file>	
			</outputs>
		</task>			
			
  </tasks>
	
</pbco>
